image: gcc

build:
  stage: test
  before_script:
    - id -a
    - echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
    - env DEBIAN_FRONTEND=noninteractive apt-get -y update
    - env DEBIAN_FRONTEND=noninteractive apt-get -y install locales cmake libhwloc-dev
  script:
    - make cmake
    - make -j4
    - make -j4 all_test_dependencies
    - env OMP_DYNAMIC=true make check ARGS="-j4"
    # okay. "cache" is only when the runners have a notion of available
    # cache server, it seems. Don't do that for now.
    # cache:
    # # paths:
    # - "*.o"
