image: gcc

build:
  stage: build
  before_script:
    - id -a
    - echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
    - env DEBIAN_FRONTEND=noninteractive apt-get -y update
    - env DEBIAN_FRONTEND=noninteractive apt-get -y install make perl locales cmake gcc python
  script:
    - make
    - make all_test_dependencies
    # okay. "cache" is only when the runners have a notion of available
    # cache server, it seems. Don't do that for now.
    # cache:
    # # paths:
    # - "*.o"

test:
  stage: test
  script:
    - make check
